/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import chart.ModelPieChart;
import chart.PieChart;
import controller.BookingController;
import controller.GuestController;
import controller.ReportController;
import controller.RoomController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Booking;
import model.Guest;
import model.Room;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.editor.ChartEditorFactory;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;





/**
 *
 * @author kushan
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    
    
    public Dashboard() {
        
        initComponents();
        
    btn_setting.setFocusPainted(false); 
    btn_bookings.setFocusPainted(false); 
    btn_guests.setFocusPainted(false); 
    btn_rooms.setFocusPainted(false); 
    btn_payment.setFocusPainted(false);
    btn_save.setFocusPainted(false); 
    btn_save.setFocusPainted(false); 
    btn_delete.setFocusPainted(false);
  
    loadTableDataRooms();
    usageOfRooms(); 
    Daily_Booking_Volume_chartLine();
    createLineChart_MonthlyIncomeTrend();
    Room_Occupancy_vs_Availability();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_rooms = new javax.swing.JButton();
        btn_guests = new javax.swing.JButton();
        btn_bookings = new javax.swing.JButton();
        btn_payment = new javax.swing.JButton();
        btn_setting = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_rooms1 = new javax.swing.JButton();
        menu = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        pieChart1 = new chart.PieChart();
        jLabel1 = new javax.swing.JLabel();
        l_report_Iroom_avalability = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        p_report = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        l_report_Income = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rooms = new javax.swing.JTable();
        txt_type = new javax.swing.JTextField();
        txt_number = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmb_status = new javax.swing.JComboBox<>();
        btn_delete = new javax.swing.JButton();
        lbl_refresh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(208, 726));

        btn_rooms.setBackground(new java.awt.Color(153, 153, 153));
        btn_rooms.setText("🏠 Rooms");
        btn_rooms.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_rooms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_rooms.addActionListener(this::btn_roomsActionPerformed);

        btn_guests.setBackground(new java.awt.Color(153, 153, 153));
        btn_guests.setText("😎 Guests");
        btn_guests.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_guests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guests.addActionListener(this::btn_guestsActionPerformed);

        btn_bookings.setBackground(new java.awt.Color(153, 153, 153));
        btn_bookings.setText("🗓️ Booking & Reservation");
        btn_bookings.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_bookings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_bookings.addActionListener(this::btn_bookingsActionPerformed);

        btn_payment.setBackground(new java.awt.Color(153, 153, 153));
        btn_payment.setText("💳 Payment & Billing");
        btn_payment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_payment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_payment.addActionListener(this::btn_paymentActionPerformed);

        btn_setting.setBackground(new java.awt.Color(153, 153, 153));
        btn_setting.setText("⚙️ Settings");
        btn_setting.setBorderPainted(false);
        btn_setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_setting.addActionListener(this::btn_settingActionPerformed);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));

        btn_rooms1.setBackground(new java.awt.Color(153, 153, 153));
        btn_rooms1.setText("📊 Reporting & Analytics");
        btn_rooms1.setActionCommand("btn_reports");
        btn_rooms1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_rooms1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_rooms1.addActionListener(this::btn_rooms1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_guests, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_bookings, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(btn_rooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_payment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_rooms1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btn_rooms1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btn_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_guests, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_bookings, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btn_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btn_setting, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 790));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel14.setText("Reporting & Analytics");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel1.setText("Usage of Rooms Type : ");

        l_report_Iroom_avalability.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 18))); // NOI18N

        javax.swing.GroupLayout l_report_Iroom_avalabilityLayout = new javax.swing.GroupLayout(l_report_Iroom_avalability);
        l_report_Iroom_avalability.setLayout(l_report_Iroom_avalabilityLayout);
        l_report_Iroom_avalabilityLayout.setHorizontalGroup(
            l_report_Iroom_avalabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );
        l_report_Iroom_avalabilityLayout.setVerticalGroup(
            l_report_Iroom_avalabilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel4.setText("Room Occupancy and Availability : ");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(365, 365, 365))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(pieChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(l_report_Iroom_avalability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(101, Short.MAX_VALUE))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pieChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_report_Iroom_avalability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Room", jPanel12);

        p_report.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 18))); // NOI18N

        javax.swing.GroupLayout p_reportLayout = new javax.swing.GroupLayout(p_report);
        p_report.setLayout(p_reportLayout);
        p_reportLayout.setHorizontalGroup(
            p_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        p_reportLayout.setVerticalGroup(
            p_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(p_report, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(p_report, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Booking", jPanel13);

        l_report_Income.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 1, 18))); // NOI18N

        javax.swing.GroupLayout l_report_IncomeLayout = new javax.swing.GroupLayout(l_report_Income);
        l_report_Income.setLayout(l_report_IncomeLayout);
        l_report_IncomeLayout.setHorizontalGroup(
            l_report_IncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        l_report_IncomeLayout.setVerticalGroup(
            l_report_IncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(l_report_Income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(l_report_Income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Income chart", jPanel14);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1206, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Room Occupancy and Availability", jPanel9);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(454, 454, 454)
                .addComponent(jLabel14)
                .addContainerGap(545, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        menu.addTab("tab1", jPanel6);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel3.setText("Booking & Reservation");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(jLabel3)
                .addContainerGap(561, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(731, Short.MAX_VALUE))
        );

        menu.addTab("tab3", jPanel3);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel5.setText("Booking & Reservation");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(jLabel5)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addContainerGap(743, Short.MAX_VALUE))
        );

        menu.addTab("tab5", jPanel5);

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel6.setText("Payment & Billing");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(452, 452, 452)
                .addComponent(jLabel6)
                .addContainerGap(593, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(745, Short.MAX_VALUE))
        );

        menu.addTab("tab6", jPanel7);

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel7.setText("Tab 7");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jLabel7)
                .addContainerGap(746, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel7)
                .addContainerGap(475, Short.MAX_VALUE))
        );

        menu.addTab("tab7", jPanel8);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel2.setText("Rooms");

        tbl_rooms.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        tbl_rooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_rooms.setToolTipText("");
        tbl_rooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_roomsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_rooms);

        txt_type.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txt_type.addActionListener(this::txt_typeActionPerformed);

        txt_number.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        txt_price.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel9.setText("Room Number : ");

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel10.setText("Room Price : ");

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel11.setText("Room Type : ");

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel12.setText("ID Search : ");

        btn_save.setBackground(new java.awt.Color(51, 102, 255));
        btn_save.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(0, 0, 0));
        btn_save.setText("Save");
        btn_save.setBorder(null);
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addActionListener(this::btn_saveActionPerformed);

        btn_update.setBackground(new java.awt.Color(102, 255, 0));
        btn_update.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(0, 0, 0));
        btn_update.setText("Update");
        btn_update.setBorder(null);
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addActionListener(this::btn_updateActionPerformed);

        txt_search.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        txt_search.addPropertyChangeListener(this::txt_searchPropertyChange);
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel13.setText("Room Status : ");

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Booked", "Available", "Pending" }));
        cmb_status.addActionListener(this::cmb_statusActionPerformed);

        btn_delete.setBackground(new java.awt.Color(255, 0, 0));
        btn_delete.setText("Delete");
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        lbl_refresh.setBackground(new java.awt.Color(153, 153, 255));
        lbl_refresh.setForeground(new java.awt.Color(102, 102, 255));
        lbl_refresh.setText("🔁🔁🔁🔁🔁🔄️🔄️🔄️🔄🔄🔄Refresh");
        lbl_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_refreshMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_refreshMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_refresh))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_number, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(214, 214, 214)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(519, 519, 519)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_delete)
                .addGap(39, 39, 39))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(943, Short.MAX_VALUE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(162, 162, 162)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(612, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(509, 509, 509)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_number, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(616, Short.MAX_VALUE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(105, 105, 105)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(524, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(244, 244, 244)))
        );

        menu.addTab("tab2", jPanel2);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -40, 1250, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingActionPerformed
         menu.setSelectedIndex(5);
       
    }//GEN-LAST:event_btn_settingActionPerformed

    private void btn_roomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roomsActionPerformed
         menu.setSelectedIndex(6);
        
    }//GEN-LAST:event_btn_roomsActionPerformed

    private void btn_guestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guestsActionPerformed
        menu.setSelectedIndex(2);
    }//GEN-LAST:event_btn_guestsActionPerformed

    private void btn_bookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookingsActionPerformed
        menu.setSelectedIndex(3);
    }//GEN-LAST:event_btn_bookingsActionPerformed

    private void btn_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paymentActionPerformed
       menu.setSelectedIndex(4);
    }//GEN-LAST:event_btn_paymentActionPerformed

    private void btn_rooms1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rooms1ActionPerformed
         menu.setSelectedIndex(0);
           usageOfRooms(); 
    }//GEN-LAST:event_btn_rooms1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
    }//GEN-LAST:event_formWindowOpened

    private void txt_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_typeActionPerformed

    private void cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_statusActionPerformed

   private void Daily_Booking_Volume_chartLine() {

    ReportController booking = new ReportController();
    Map<String, Integer> data = booking.getDailyBookings();   

    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    for (Map.Entry<String, Integer> entry : data.entrySet()) {
        String date = entry.getKey();         
        int count = entry.getValue();         
        dataset.addValue(count, "Bookings", date);
    }

    JFreeChart chart = ChartFactory.createBarChart(
        "Daily Booking Volume",     
        "Date",                      
        "Bookings Count",            
        dataset,
        PlotOrientation.VERTICAL,
        true,
        true,
        false
    );

    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setSize(p_report.getWidth(), p_report.getHeight());
    chartPanel.setVisible(true);

    p_report.removeAll();
    p_report.add(chartPanel);
    p_report.revalidate();
    p_report.repaint();
}

   private void createLineChart_MonthlyIncomeTrend() {

    ReportController rc = new ReportController();
    Map<String, Double> data = rc.getMonthlyIncomeTrend();

    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    for (Map.Entry<String, Double> entry : data.entrySet()) {
        dataset.addValue(entry.getValue(), "Income (Rs)", entry.getKey()); 
    }

    JFreeChart lineChart = ChartFactory.createLineChart(
        "Monthly Income Trend",
        "Month",
        "Income (Rs)",
        dataset,
        PlotOrientation.VERTICAL,
        true,
        true,
        false
    );

    ChartPanel chartPanel = new ChartPanel(lineChart);
    chartPanel.setSize(l_report_Income.getWidth(), l_report_Income.getHeight());

    l_report_Income.removeAll();
    l_report_Income.add(chartPanel);
    l_report_Income.revalidate();
    l_report_Income.repaint();
}
   
   private void Room_Occupancy_vs_Availability() {
    
    ReportController rc = new ReportController();
    Map<String, Integer> data = rc.getRoomOccupancyReport();

    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    dataset.addValue(data.get("Occupied"), "Rooms", "Occupied");
    dataset.addValue(data.get("Available"), "Rooms", "Available");

    JFreeChart chart = ChartFactory.createBarChart(
            "Room Occupancy vs Availability",
            "Room Status",
            "Number of Rooms",
            dataset
    );

    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setSize(l_report_Iroom_avalability.getWidth(), l_report_Iroom_avalability.getHeight());

    l_report_Iroom_avalability.removeAll();
    l_report_Iroom_avalability.add(chartPanel);
    l_report_Iroom_avalability.revalidate();
    l_report_Iroom_avalability.repaint();
}


    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        
        try{
            
   if (txt_number.getText().isEmpty() ||txt_type.getText().isEmpty() ||txt_price.getText().isEmpty() ||cmb_status.getSelectedItem() == null) {

    JOptionPane.showMessageDialog(this, "Please fill all fields!");
    return; 
}
            
        RoomController rc = new  RoomController();
       
       boolean result = rc.addroom(txt_number.getText(), txt_type.getText(), Double.parseDouble(txt_price.getText()), cmb_status.getSelectedItem().toString());
       
       if(result){
            
            JOptionPane.showMessageDialog(this, "Room Added successfully completed !!");

        }else{
            JOptionPane.showMessageDialog(this, "Room Added error  !!");
           
        }
       
       loadTableDataRooms();
         usageOfRooms(); 
            
        }catch(NumberFormatException ee){
            
            JOptionPane.showMessageDialog(this, "Invalid price! Only numbers allowed. Error : "+ ee.getMessage());
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "Somthing went wrong Error : "+ e.getMessage());
        }
      
    }//GEN-LAST:event_btn_saveActionPerformed

    private void tbl_roomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_roomsMouseClicked
        
        DefaultTableModel model = (DefaultTableModel)tbl_rooms.getModel();
        
        int index = tbl_rooms.getSelectedRow();
        
        txt_number.setText(model.getValueAt(index, 1).toString());
        txt_type.setText(model.getValueAt(index, 2).toString());
        txt_price.setText(model.getValueAt(index, 3).toString());
        txt_search.setText(model.getValueAt(index, 0).toString());
        cmb_status.setSelectedItem(model.getValueAt(index, 4).toString());
        
        
    }//GEN-LAST:event_tbl_roomsMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
       try{
        
        if (txt_number.getText().isEmpty() ||txt_type.getText().isEmpty() ||txt_price.getText().isEmpty() ||cmb_status.getSelectedItem() == null) {

    JOptionPane.showMessageDialog(this, "Please fill all fields!");
    return; 
}

        RoomController rc = new RoomController();
        
        boolean result = rc.updateroom(Integer.parseInt(txt_search.getText()),txt_number.getText(), txt_type.getText(), Double.parseDouble(txt_price.getText()), cmb_status.getSelectedItem().toString());
        if(result){
            
            JOptionPane.showMessageDialog(this, "Room Upadate successfully completed !!");

        }else{
            JOptionPane.showMessageDialog(this, "Room Upadate error  !!");
        }
        loadTableDataRooms();
          usageOfRooms(); 
       }catch(NumberFormatException ee){
           
           JOptionPane.showMessageDialog(this, "Invalid price! Only numbers allowed. Error : "+ ee.getMessage());
           
       }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "Somthing went wrong Error : "+ e.getMessage());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
       
                RoomController rc = new RoomController();
                boolean result =  rc.deleteroom(Integer.parseInt(txt_search.getText()));
                
                if(result){
                    JOptionPane.showMessageDialog(this, "Room Delete successfully completed !!");
                }else{
                    JOptionPane.showMessageDialog(this, "Room Delete  error  or Not Found !!");
                }
                
                loadTableDataRooms();
                  usageOfRooms(); 

    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_searchPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_searchPropertyChange
      

    }//GEN-LAST:event_txt_searchPropertyChange

    private void lbl_refreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_refreshMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_refreshMousePressed

    private void lbl_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_refreshMouseClicked
      loadTableDataRooms();
      
    }//GEN-LAST:event_lbl_refreshMouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        
        DefaultTableModel ob = (DefaultTableModel) tbl_rooms.getModel();
        TableRowSorter<DefaultTableModel>  obj = new TableRowSorter<>(ob);
        tbl_rooms.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(txt_search.getText()));
        
    }//GEN-LAST:event_txt_searchKeyReleased

    
    private void loadTableDataRooms(){
        
        
        
        RoomController rc = new RoomController();
    List<Room> dataList = rc.getallrooms();
    
    String[] columnNames = {"ID", "Number", "Type", "Price", "Status"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);

    for (Room obj : dataList) {
       
        model.addRow(new Object[]{
            obj.getID(),
            obj.getNumber(),
            obj.getType(),
            obj.getPrice(),
            obj.getStatus()
                
       
        } );
    }

    tbl_rooms.setModel(model);
    usageOfRooms();
    }
    
 private void usageOfRooms(){
    
    pieChart1.clearData();
    ReportController rc = new ReportController();
    Map<String , Integer> datalist = rc.getRoomTypeReport();
    int index = 0;
    
    for (Map.Entry<String, Integer> entry : datalist.entrySet()) {
        String roomType = entry.getKey();
        int count = entry.getValue();

        
        pieChart1.addData(new ModelPieChart(roomType, count, getcolor(index++)));
    }
}

private Color getcolor(int index){
    Color[] colorList = {
        new Color(255, 99, 132),
        new Color(54, 162, 235),
        new Color(255, 206, 86),
        new Color(75, 192, 192),
        new Color(153, 102, 255),
        new Color(255, 159, 64)
    };
    return colorList[index % colorList.length];
}

    
        
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bookings;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_guests;
    private javax.swing.JButton btn_payment;
    private javax.swing.JButton btn_rooms;
    private javax.swing.JButton btn_rooms1;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_setting;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel l_report_Income;
    private javax.swing.JPanel l_report_Iroom_avalability;
    private javax.swing.JLabel lbl_refresh;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JPanel p_report;
    private chart.PieChart pieChart1;
    private javax.swing.JTable tbl_rooms;
    private javax.swing.JTextField txt_number;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_type;
    // End of variables declaration//GEN-END:variables
}
